SELECT * FROM project_1.customer_behavior;
use project_1;

-- Q1. What is the total revenue generated by male vs female customers?
select gender,SUM(purchase_amount)
from project_1.customer_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,age,gender,purchase_amount,discount_applied
from project_1.customer_behavior
where discount_applied='yes' and purchase_amount>(select avg(purchase_amount) from project_1.customer_behavior );

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as average_rating
from project_1.customer_behavior
group by item_purchased
order by avg(review_rating)desc
limit 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) as average_amt
from project_1.customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select count(customer_id),subscription_status,sum(purchase_amount) as revenue,round(avg(purchase_amount),2) as average_amt
from project_1.customer_behavior
group by subscription_status;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*))*100 as disc_per
from project_1.customer_behavior
group by item_purchased
order by disc_per desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with  customer_type as (
select customer_id,previous_purchases,case when previous_purchases=1 then "New"
										  when previous_purchases between 2 and 10 then "Returning"
                                          else "Loyal" end as customer_segment
from project_1.customer_behavior
)
select customer_segment,count(customer_id) as customer_count
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category,item_purchased,count(customer_id) as total_orders,row_number() over(partition by category order by count(customer_id) desc) as item_rank
from project_1.customer_behavior
group by item_purchased,category
)
select * from item_count
where item_rank<=3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_byers
from project_1.customer_behavior
where previous_purchases>5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from project_1.customer_behavior
group by age_group
order by total_revenue desc;
